language: go
go:
- 1.17.6
env:
- TF_ACC=1 MOCK_STATUS=1 CGO_ENABLED=0
before_install:
- go get github.com/mitchellh/gox
script:
- go test -v
- gox -osarch="darwin/amd64 freebsd/386 freebsd/amd64 freebsd/arm linux/386 linux/amd64
  linux/arm openbsd/386 openbsd/amd64 solaris/amd64 windows/386 windows/amd64" -output="out/terraform_{{.OS}}_{{.Arch}}"
  -verbose -ldflags '-s -w -extldflags "-static"' ./...
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  api_key: $RELEASES_API_KEY
  file: out/*
  on:
    tags: true

